services:
  birthdays_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./birthdays_volume:/data/db
    restart: unless-stopped

  birthday_core:
    depends_on:
      - "birthdays_db"
    build:
      context: ./core
    environment:
      DB_HOST: birthdays_db
      DB_PORT: 27017
      DB_NAME: birthdays
    ports:
      - "4000:4000"
    restart: unless-stopped
